#!/bin/bash

RESOURCE_DIR="$HOME/.local/share/nvim-ide"

source $RESOURCE_DIR/config

export HOST_UID=$(id -u)
export HOST_GID=$(id -g)

REAL=""
CURRENT_PATH=""
NVIM_PATH=""

if [ ! -z "$1" ]; then
	REAL="$(realpath $1)"
else
	REAL="$(realpath .)"
fi

if [ -d "$REAL" ]; then
	if [ -z "$1" ]; then
		NVIM_PATH=""
	else
		NVIM_PATH=" ."
	fi
	CURRENT_PATH="$REAL"
else
	NVIM_PATH=" $(basename $REAL)"
	CURRENT_PATH="$(dirname $REAL)"
fi

if [ -z "$(docker images -q $DOCKER_IMAGE)" ]; then
	echo "Image does not exist. Building now..."
	CMD="docker build --build-arg UID=$HOST_UID --build-arg GID=$HOST_GID -t $DOCKER_IMAGE $RESOURCE_DIR"
	$CMD
fi

if [ ! "$(docker ps -aq -f name=$DOCKER_CONTAINER)" ]; then
	echo "Container does not exist. Creating now..."
	CMD="docker run -d \
        --name $DOCKER_CONTAINER \
        -v nvim_state:/home/nonroot/.local/state/nvim \
        -v nvim_share:/home/nonroot/.local/share/nvim \
        -v $NVIM_CONFIG_DIR:/home/nonroot/.config/nvim \
        -v $HOME/.ssh:/home/nonroot/.ssh \
        $DOCKER_IMAGE"
	$CMD
fi

CMD="docker run --rm -it \
    --net=host -e DISPLAY=$DISPLAY \
    --volumes-from $DOCKER_CONTAINER \
    -v $CURRENT_PATH:/home/nonroot/workspace \
    $DOCKER_IMAGE nvim$NVIM_PATH"
$CMD
